### ISSUE TITLE
work progress - checklist

### ISSUE THREAD

**Issue by carlacotas** [carlacotas/data-science-kaggle-Titanic-Project#1]
This issue pretends to be the guideline for the data science work to be developed in this project. It is based on the steps presented by 
Ken Jee 
- https://www.youtube.com/watch?v=I3FBJdiExcg
- https://www.kaggle.com/kenjee/titanic-project-example

**Comment by carlacotas** [comment]
**Checklist:**

- [x]  Understand the shape of the data (Histograms, box plots, etc.)
- [x]  Data Cleaning
- [x]  Data Exploration
- [x]  Feature Engineering
- [x]  Data Preprocessing for Model
- [ ]  Basic Model Building
- [ ]  Model Tuning
- [ ]  Ensemble Modle Building
- [ ]  Results
